### ISSUE TITLE
Getting cannot find module running index.js file

### ISSUE THREAD

**Issue by basilinjoe** [stimulsoft/Samples-JS#1]
Hey am getting cannot find modules `rgbcolor` and `stackblur` and on installing this modules am getting a `Element not defined` error 

```
ReferenceError: Element is not defined
    at D:\projects\node\01. Load Report and Saving Rendered Report\node_modules\
stimulsoft-reports-js\stimulsoft.reports.js:118:29040
    at e (D:\projects\node\01. Load Report and Saving Rendered Report\node_modul
es\stimulsoft-reports-js\stimulsoft.reports.js:117:177)
    at Object.<anonymous> (D:\projects\node\01. Load Report and Saving Rendered
Report\node_modules\stimulsoft-reports-js\stimulsoft.reports.js:117:256)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\projects\node\01. Load Report and Saving Rendered
Report\node_modules\stimulsoft-reports-js\index.js:1:80)

```

**Comment by kubekin** [comment]
Hello, Joe!

Sorry for troubles with our product!

At this moment, this problem is solved. Please redownload our code from
GitHub.

Let me know if you need any additional help.

Thank you.



2016-04-19 10:33 GMT+03:00 Basilin Joe <notifications@github.com>:
