### ISSUE TITLE
Who can tell which version of dependency opentype used in Samples for NodeJS?

### ISSUE THREAD

**Issue by molokovskikh** [stimulsoft/Samples-JS#10]
$ npm install 
npm WARN engine mssql@4.0.4: wanted: {"node":">=4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN engine tedious@2.0.0: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
npm WARN engine generic-pool@3.1.8: wanted: {"node":">= 4"} (current: {"node":"0.12.17","npm":"2.15.1"})
stimulsoft-reports-js@2017.1.11 node_modules/stimulsoft-reports-js
├── rgbcolor@0.0.4
├── stackblur@1.0.0
├── xmldoc@1.1.0 (sax@1.2.4)
├── mysql@2.14.1 (sqlstring@2.2.0, safe-buffer@5.1.1, bignumber.js@4.0.2, readable-stream@2.3.3)
├── opentype.js@0.6.9 (tiny-inflate@1.0.2)
├── sync-request@3.0.1 (http-response-object@1.1.0, concat-stream@1.6.0, then-request@2.2.0)
├── pg@4.5.7 (packet-reader@0.2.0, js-string-escape@1.0.1, pg-connection-string@0.1.3, buffer-writer@1.0.1, generic-pool@2.4.2, semver@4.3.6, pg-types@1.12.1, pgpass@0.0.3)
├── jszip@2.6.1 (pako@1.0.6)
├── xlsx@0.10.9 (exit-on-epipe@1.0.1, commander@2.11.0, adler-32@1.1.0, crc-32@1.1.1, cfb@0.12.1, ssf@0.10.1, codepage@1.10.2)
└── mssql@4.0.4 (generic-pool@3.1.8, debug@2.6.9, tedious@2.0.0)
Stimulsoft Reports loaded

$ node index
Samples-JS/Node.js/01. Load Report and Saving Rendered Report/node_modules/stimulsoft-reports-js/node_modules/opentype.js/src/opentype.js:179
    var data = new DataView(buffer, 0);
               ^
TypeError: First argument to DataView constructor must be an ArrayBuffer
    at new DataView (native)
    at Object.parseBuffer [as parse] (/home/sergey/touchStimulsoft/Samples-JS/Node.js/01. Load Report and Saving Rendered Report/node_modules/stimulsoft-reports-js/node_modules/opentype.js/src/opentype.js:179:16)
    at Function.t.addOpentypeFontFile (/home/sergey/touchStimulsoft/Samples-JS/Node.js/01. Load Report and Saving Rendered Report/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:134:79099)
    at Object.<anonymous> (/home/sergey/touchStimulsoft/Samples-JS/Node.js/01. Load Report and Saving Rendered Report/index.js:6:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

**Comment by molokovskikh** [comment]
Sorry! I'm stupid ))
Don't use older version nodejs.
With node version v7.7.1 sample working great!
