### ISSUE TITLE
Bugs in latest version 

### ISSUE THREAD

**Issue by mille-nium** [stimulsoft/Samples-JS#17]
All of samples cannot be runned with the latest version of `stimulsoft-reports-js`, which is in `package.json`. Trying to run it giving me this:
```
function __default(e){return Stimulsoft.System.Activator.createInstance(e)}var __extends=this&&this.__extends||function(){var e=function(t,r){return(e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(t,r)};return function(t,r){function n(){this.constructor=t}e(t,r),t.prototype=null===r?Object.create(r):(n.prototype=r.prototype,new n)}}(),Stimulsoft;!function(e){var t;!function(e){var t;!function(e){var t=function(){function t(){this._list=[]}return Object.defineProperty(t.prototype,"list",{get:function(){return this._list},enumerable:!0,configurable:!0}),t.prototype.implements=function(){return[e.ICollection]},Object.defineProperty(t.prototype,"count",{get:function(){return this._list.length},enumerable:!0,configurable:!0}),t.prototype.clear=function(){this.onClear(),

ReferenceError: navigator is not defined
    at Function.get [as currentCulture] (/home/mille_nium/projects/Samples-JS/Node.js/03. Export Rendered Report to PDF-file/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:38:252776)
    at /home/mille_nium/projects/Samples-JS/Node.js/03. Export Rendered Report to PDF-file/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:39:214393
    at /home/mille_nium/projects/Samples-JS/Node.js/03. Export Rendered Report to PDF-file/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:39:214410
    at /home/mille_nium/projects/Samples-JS/Node.js/03. Export Rendered Report to PDF-file/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:39:214429
    at /home/mille_nium/projects/Samples-JS/Node.js/03. Export Rendered Report to PDF-file/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:39:214471
    at Object.<anonymous> (/home/mille_nium/projects/Samples-JS/Node.js/03. Export Rendered Report to PDF-file/node_modules/stimulsoft-reports-js/stimulsoft.reports.js:39:214499)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
```
However, everything works with `2018.3.3` version

**Comment by morgenweck** [comment]
Will this be addressed?
